### ISSUE TITLE
Not working with brunch

### ISSUE THREAD

**Issue by optikfluffel** [r-icarus/phoenix-resinio-example#1]
Hi,

I've tried to fiddle your example and [a section from Phoenix' deployment guide](http://www.phoenixframework.org/docs/deployment#section-putting-it-all-together) together to something like this:

``` Dockerfile
FROM ricarus/rpi-raspbian-elixir
ADD . /my_app
ENV PATH /elixir/bin:$PATH
ENV LC_ALL en_US.UTF-8
ENV MIX_ENV prod
ENV PORT 80
EXPOSE 80
WORKDIR /my_app
RUN mix deps.get --only prod
RUN mix compile
RUN brunch build --production
RUN MIX_ENV=prod mix phoenix.digest
CMD mix phoenix.server
```

Now building the image stopped because brunch isn't available. Do you plan to include node.js and maybe even brunch in [your Docker image](https://hub.docker.com/r/ricarus/rpi-raspbian-elixir/) or would I have to come up with my own one?

Thanks so far.

**Comment by r-icarus** [comment]
The image doesn't have npm support yet. But I can add it over the weekend. In the meantime you can compile the assets locally and add priv/static to the git repository if you want to see your app running.
